### ISSUE TITLE
Not working because share via Messenger

### ISSUE THREAD

**Issue by Xi-Plus** [domen111/Draw-Graph#1]
Share this link https://domen111.github.io/Draw-Graph/?data=1%202&directed=0&ignore=0 on Google Chrome for Android. Because of Facebook Link Preview, it was converted into https://domen111.github.io/Draw-Graph/?data=1+2&directed=0&ignore=0 . So it is not working.

**Comment by domen111** [comment]
I use javascript function `decodeURIComponent` which doesn't support `+` as space to decode the url parameters. An easy way I know to resolve this problem is just replace `+` to `%20` manually, or is there another better ways?

**Comment by Xi-Plus** [comment]
How about `encodeURIComponent` twice?
